// Auto-itemised IPD billing helper.
//
// The hospital wants every clinical event for an admitted patient — lab
// orders, radiology orders, prescriptions, procedures — to land as a
// line item on the patient's running IPD invoice the moment it happens.
// Families can settle the bill in parts during the stay; on discharge
// the same invoice is finalised. Dialysis-only patients are NOT covered
// here: they pay per-session at OPD, so their workflow doesn't have an
// admission row to attach charges to.
//
// Design notes:
//
// 1. There is exactly ONE active IPD invoice per admission. The first
//    billable event creates it; every subsequent event appends a line
//    item and re-derives subtotal/total/balance, preserving any
//    discount that was already applied.
//
// 2. Pricing is fetched from the master tables (LabTestMaster,
//    RadiologyTestMaster, ProcedureMaster, Drug). If a price is
//    missing for any item, `requirePrice()` throws `MissingPriceError`
//    and the calling endpoint surfaces it as 422 — the user has chosen
//    to refuse orders that can't be priced rather than letting a ₹0
//    line slip through (master data is the source of truth).
//
// 3. Bed-day charges are NOT stored as line items here. They are
//    computed at fetch time in /api/ipd-billing/:admissionId so the
//    bed total stays current without a daily cron writing rows.
//
// 4. All append operations must run inside the same Prisma transaction
//    as the source row create (lab order, prescription, etc.) so a
//    crash between the source row and its line item can't leave the
//    invoice out of sync with the clinical record.

import { Prisma } from '@prisma/client';
import { prisma } from './prisma';

export class MissingPriceError extends Error {
  code = 'MISSING_PRICE';
  constructor(public itemType: string, public itemRef: string) {
    super(`No master-data price found for ${itemType} "${itemRef}"`);
    this.name = 'MissingPriceError';
  }
}

export interface LineItem {
  // Stable id within the items[] array — uuid-ish string the FE uses as
  // a key. Generated by the caller (lab order id + test code, etc.).
  id: string;
  category: 'lab' | 'radiology' | 'pathology' | 'pharmacy' | 'procedure' | 'consultation' | 'bed' | 'other';
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
  // Source row reference so the bill can link back to the order /
  // prescription / etc. Both fields are optional because some line
  // items (e.g. manual adjustments) won't have a source.
  sourceType?: string;
  sourceId?: string;
  // ISO timestamp of the event that produced this line.
  occurredAt: string;
}

type TxClient = Prisma.TransactionClient;

// Returns the active admission row for a patient, or null if the patient
// isn't currently admitted. Used both to decide whether to auto-bill and
// to attach the invoice to the right encounter.
//
// "Active" here means: no dischargeDate AND status in (active, admitted,
// in_progress). The schema doesn't enforce a strict enum, so we accept
// the historical variants we know about.
export async function findActiveAdmission(
  tx: TxClient | typeof prisma,
  tenantId: string,
  patientId: string,
) {
  return tx.admission.findFirst({
    where: {
      patientId,
      dischargeDate: null,
      status: { in: ['active', 'admitted', 'in_progress'] },
      patient: { tenantId },
    },
    select: { id: true, encounterId: true, patientId: true },
  });
}

// Resolves price for a billable item. Throws MissingPriceError if the
// master row is missing or has price <= 0 (a zero price is treated as
// "unknown" rather than "free" — explicit zero items should be flagged
// in master data with a different mechanism if ever needed).
export async function requireLabTestPrice(tx: TxClient | typeof prisma, testIdOrCode: string): Promise<{ id: string; name: string; price: number }> {
  const row = await tx.labTestMaster.findFirst({
    where: { OR: [{ id: testIdOrCode }, { code: testIdOrCode }] },
    select: { id: true, name: true, price: true },
  });
  if (!row || Number(row.price) <= 0) throw new MissingPriceError('lab_test', testIdOrCode);
  return { id: row.id, name: row.name, price: Number(row.price) };
}

export async function requireRadiologyTestPrice(tx: TxClient | typeof prisma, testIdOrCode: string): Promise<{ id: string; name: string; price: number }> {
  const row = await tx.radiologyTestMaster.findFirst({
    where: { OR: [{ id: testIdOrCode }, { code: testIdOrCode }] },
    select: { id: true, name: true, price: true },
  });
  if (!row || Number(row.price) <= 0) throw new MissingPriceError('radiology_test', testIdOrCode);
  return { id: row.id, name: row.name, price: Number(row.price) };
}

export async function requireProcedurePrice(tx: TxClient | typeof prisma, procIdOrCode: string): Promise<{ id: string; name: string; price: number }> {
  const row = await tx.procedureMaster.findFirst({
    where: { OR: [{ id: procIdOrCode }, { code: procIdOrCode }] },
    select: { id: true, name: true, price: true },
  });
  if (!row || Number(row.price) <= 0) throw new MissingPriceError('procedure', procIdOrCode);
  return { id: row.id, name: row.name, price: Number(row.price) };
}

// Drugs are matched by name (case-insensitive) because the legacy
// Prescription.drugs JSON only stores names, not Drug.id. If multiple
// SKUs share the same display name (different strengths/forms), the
// first active row wins — operators should keep master data clean for
// the rest. Hospitals that want strict id-based matching can update
// the prescription create flow to pass drug ids.
export async function requireDrugPriceByName(tx: TxClient | typeof prisma, drugName: string): Promise<{ id: string; name: string; price: number }> {
  if (!drugName || !drugName.trim()) throw new MissingPriceError('drug', '(empty name)');
  const row = await tx.drug.findFirst({
    where: { name: { equals: drugName.trim(), mode: 'insensitive' }, isActive: true },
    select: { id: true, name: true, price: true },
  });
  if (!row || Number(row.price) <= 0) throw new MissingPriceError('drug', drugName);
  return { id: row.id, name: row.name, price: Number(row.price) };
}

// Gets the open IPD invoice for an admission's encounter, or creates
// an empty draft if none exists. Encounter-scoped (not admission-
// scoped) because Invoice has FKs to Encounter, not Admission, and the
// IPD admission always has exactly one Encounter (1-to-1).
export async function getOrCreateActiveIpdInvoice(
  tx: TxClient,
  args: { patientId: string; encounterId: string },
) {
  // Open invoice = same encounter, type='ipd', and not yet settled.
  // 'paid' is a terminal state; 'cancelled' likewise. Anything else
  // (draft, final, partial, overpaid) is still in play.
  const existing = await tx.invoice.findFirst({
    where: {
      encounterId: args.encounterId,
      type: 'ipd',
      status: { notIn: ['paid', 'cancelled'] },
    },
  });
  if (existing) return existing;

  return tx.invoice.create({
    data: {
      patientId: args.patientId,
      encounterId: args.encounterId,
      type: 'ipd',
      items: [],
      subtotal: 0,
      discount: 0,
      tax: 0,
      total: 0,
      paid: 0,
      balance: 0,
      status: 'draft',
    },
  });
}

// Appends one or more line items to an invoice and recomputes the
// money columns. The existing `discount` is preserved as an absolute
// amount (matching the discount endpoint contract); tax is recomputed
// only if there's an existing taxPercent stored — for the current
// schema there's no tax-percent column, so tax stays as-is.
export async function appendLineItems(
  tx: TxClient,
  invoiceId: string,
  newItems: LineItem[],
): Promise<void> {
  if (!newItems.length) return;

  const inv = await tx.invoice.findUnique({ where: { id: invoiceId } });
  if (!inv) throw new Error(`Invoice ${invoiceId} not found`);

  const currentItems = Array.isArray(inv.items) ? (inv.items as unknown as LineItem[]) : [];
  // De-dupe by (sourceType, sourceId, id) — if the caller retries an
  // order create, the second pass shouldn't double-bill. The check is
  // belt-and-braces; the upstream transactional boundary should
  // already prevent this in normal operation.
  const existingKeys = new Set(
    currentItems.map((it) => `${it.sourceType || ''}::${it.sourceId || ''}::${it.id}`),
  );
  const filteredNew = newItems.filter(
    (it) => !existingKeys.has(`${it.sourceType || ''}::${it.sourceId || ''}::${it.id}`),
  );
  if (!filteredNew.length) return;

  const mergedItems = [...currentItems, ...filteredNew];

  const newSubtotal = +mergedItems.reduce((s, it) => s + Number(it.total || 0), 0).toFixed(2);
  const discount = Number(inv.discount || 0);
  const tax = Number(inv.tax || 0);
  const newTotal = +(newSubtotal + tax - discount).toFixed(2);
  const paid = Number(inv.paid || 0);
  const newBalance = +(newTotal - paid).toFixed(2);

  await tx.invoice.update({
    where: { id: invoiceId },
    data: {
      items: mergedItems as unknown as Prisma.InputJsonValue,
      subtotal: newSubtotal,
      total: newTotal,
      balance: newBalance,
      // Bump 'draft' to 'final' once there's a real line on the bill.
      // 'paid'/'cancelled' wouldn't have been returned by
      // getOrCreateActiveIpdInvoice so we don't need to guard them.
      status: inv.status === 'draft' ? 'draft' : inv.status,
    },
  });
}

// Convenience wrapper: idempotently bill a batch of lab tests for a
// patient if they're currently admitted. Returns the line items added
// (empty array if the patient isn't admitted — auto-bill only applies
// to IPD). Throws MissingPriceError on a per-item basis so the caller
// can abort the whole order.
export async function autoBillLabTests(
  tx: TxClient,
  args: { tenantId: string; patientId: string; orderId: string; tests: Array<{ id?: string; code?: string; testId?: string; name?: string; quantity?: number }>; orderedAt: Date },
): Promise<LineItem[]> {
  const admission = await findActiveAdmission(tx, args.tenantId, args.patientId);
  if (!admission || !admission.encounterId) return [];

  const lines: LineItem[] = [];
  for (const t of args.tests) {
    const ref = t.id || t.code || t.testId || t.name || '';
    if (!ref) throw new MissingPriceError('lab_test', '(no id/code/name on test)');
    const priced = await requireLabTestPrice(tx, ref);
    const qty = Math.max(1, Number(t.quantity || 1));
    lines.push({
      id: `${args.orderId}-${priced.id}`,
      category: 'lab',
      description: priced.name,
      quantity: qty,
      unitPrice: priced.price,
      total: +(priced.price * qty).toFixed(2),
      sourceType: 'lab_order',
      sourceId: args.orderId,
      occurredAt: args.orderedAt.toISOString(),
    });
  }

  const invoice = await getOrCreateActiveIpdInvoice(tx, {
    patientId: args.patientId,
    encounterId: admission.encounterId,
  });
  await appendLineItems(tx, invoice.id, lines);
  return lines;
}

export async function autoBillRadiologyTests(
  tx: TxClient,
  args: { tenantId: string; patientId: string; orderId: string; tests: Array<{ id?: string; code?: string; testId?: string; name?: string; quantity?: number }>; orderedAt: Date },
): Promise<LineItem[]> {
  const admission = await findActiveAdmission(tx, args.tenantId, args.patientId);
  if (!admission || !admission.encounterId) return [];

  const lines: LineItem[] = [];
  for (const t of args.tests) {
    const ref = t.id || t.code || t.testId || t.name || '';
    if (!ref) throw new MissingPriceError('radiology_test', '(no id/code/name on test)');
    const priced = await requireRadiologyTestPrice(tx, ref);
    const qty = Math.max(1, Number(t.quantity || 1));
    lines.push({
      id: `${args.orderId}-${priced.id}`,
      category: 'radiology',
      description: priced.name,
      quantity: qty,
      unitPrice: priced.price,
      total: +(priced.price * qty).toFixed(2),
      sourceType: 'radiology_order',
      sourceId: args.orderId,
      occurredAt: args.orderedAt.toISOString(),
    });
  }

  const invoice = await getOrCreateActiveIpdInvoice(tx, {
    patientId: args.patientId,
    encounterId: admission.encounterId,
  });
  await appendLineItems(tx, invoice.id, lines);
  return lines;
}

// Prescription auto-billing for admitted patients. The drugs JSON shape
// is { name, dose?, frequency?, days?, quantity? } — we bill by name
// using Drug.price, multiplying by `quantity` if present, otherwise 1
// unit per drug entry. Ops can refine the quantity model later (e.g.
// derive from dose+days) without changing this helper's signature.
export async function autoBillPrescription(
  tx: TxClient,
  args: { tenantId: string; patientId: string; prescriptionId: string; drugs: Array<{ name: string; quantity?: number }>; issuedAt: Date },
): Promise<LineItem[]> {
  const admission = await findActiveAdmission(tx, args.tenantId, args.patientId);
  if (!admission || !admission.encounterId) return [];

  const lines: LineItem[] = [];
  for (const d of args.drugs) {
    const priced = await requireDrugPriceByName(tx, d.name);
    const qty = Math.max(1, Number(d.quantity || 1));
    lines.push({
      id: `${args.prescriptionId}-${priced.id}`,
      category: 'pharmacy',
      description: priced.name,
      quantity: qty,
      unitPrice: priced.price,
      total: +(priced.price * qty).toFixed(2),
      sourceType: 'prescription',
      sourceId: args.prescriptionId,
      occurredAt: args.issuedAt.toISOString(),
    });
  }

  const invoice = await getOrCreateActiveIpdInvoice(tx, {
    patientId: args.patientId,
    encounterId: admission.encounterId,
  });
  await appendLineItems(tx, invoice.id, lines);
  return lines;
}
